import {useEffect, useState} from 'react';
import Head from 'next/head'
import Image from 'next/image'

// Styles
import styles from '../styles/Home.module.css'

// Utils
import getClients from "../utility/getClients";

// Components
import ClientsList from "../components/ClientsList";

const getInitialProps = async () => {
    const clients = await getClients();

    return {clients};
}

function Home({clients: ssrClients}) {
    const [clients, setClients] = useState(ssrClients);

    useEffect(() => {
        getClients(setClients).catch(console.error);
    }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>My Simple App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    My Simple App
                </h1>
                <ClientsList clients={clients} />
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
                </a>
            </footer>
        </div>
    )
}

Home.getInitialProps = getInitialProps;

export default Home;
